# ./docker-compose.yml

version: '3.4'

services:
  graphql:
    build:
      context: ../projects/pjx-graphql-apollo
    container_name: pjx-graphql-apollo-dev
    command: npm run dev
    volumes:
      - .:/usr/api
    ports:
      - 4000:4000

networks:
  pjx-network:
    driver: bridge

